export enum BacktestEventType {
  MARKET = 'MARKET',
  OPTION_CHAIN = 'OPTION_CHAIN',
  SIGNAL = 'SIGNAL',
  ORDER_FILLED = 'ORDER_FILLED',
  POSITION_OPENED = 'POSITION_OPENED',
  POSITION_CLOSED = 'POSITION_CLOSED',
}
